function adaugaJucatori(){
    transferuri.push(new transferPlayer('Modric'     ,98,'MIDFIELDER',0 ));
    transferuri.push(new transferPlayer('Reus'       ,98,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Sterling'   ,98,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Di Maria'   ,98,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Hazard'     ,97,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Sanchez'    ,97,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Kane'       ,97,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Salah'      ,97,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Messi'      ,97,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Ronaldo'    ,97,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Marcelo'    ,97,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
	transferuri.push(new transferPlayer('De bruyne'  ,96,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Lewandowski',95,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
	transferuri.push(new transferPlayer('Griezmann'  ,96,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Courtois'   ,96,'GOALKEEPER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Alaba'      ,96,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Bonucci'    ,96,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Neymar'     ,96,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Busquets'   ,96,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Benatia'    ,96,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Rakitic'    ,96,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Depay'      ,96,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Cavani'     ,96,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Kroos'      ,96,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Son'        ,96,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Bale'       ,95,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Suarez'     ,95,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Godin'      ,95,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('D.Luiz'     ,95,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Perisic'    ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Mkhitaryan' ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Coutinho'   ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Roudriguez' ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Pogba'      ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Insigne'    ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Dybala'     ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Isco'       ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('De Gea'     ,95,'GOALKEEPER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Aguero'     ,95,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Vidal'      ,95,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Aubameyang' ,94,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('T.Silva'    ,94,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Kante'      ,94,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Gotze'      ,94,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Manolas'    ,94,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Candreva'   ,94,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Casemiro'   ,94,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Ozil'       ,94,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Mertens'    ,94,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Iniesta'    ,94,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Cuadrado'   ,94,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Calejon'    ,93,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Chiellini'  ,93,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Lozano'     ,93,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Lingard'    ,93,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Lemar'      ,93,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Marquinhos' ,93,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Mandzukic'  ,93,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('G.Jesus'    ,93,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Wijnaldum'  ,93,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Iheanacho'  ,93,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Van Persie' ,93,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Meunier'    ,93,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Koulibaly'  ,93,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Trippier'   ,93,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Buffon'     ,93,'GOALKEEPER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Neuer'      ,92,'GOALKEEPER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Handanovic' ,92,'GOALKEEPER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Higuain'    ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Dele Alli'  ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Alba'       ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Eriksen'    ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Sokratis'   ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Miranda'    ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Ibrahimovic',92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Brandt'     ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Xhaka'      ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Batshuaiy'  ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Forsberg'   ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Martial'    ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Florenzi'   ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('S.Mane'     ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Muller'     ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Varane'     ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Hummels'    ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Coleman'    ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('B.Silva'    ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Ramsey'     ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Bartra'     ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Kagawa'     ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Icardi'     ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Imobile'    ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Umtiti'     ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Naldo'      ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Pepe'       ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Valencia'   ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Tevez'      ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Akinfeev'   ,92,'GOALKEEPER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Cheryshev'  ,92,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Smolov'     ,92,'FORWARD'   ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Bailly'     ,92,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Pique'      ,91,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Granqvist'  ,91,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Otamendi'   ,91,'DEFENDER'  ,transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Quaresma'   ,91,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Kalou'      ,91,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Budescu'    ,90,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Chipciu'    ,90,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Tatarusanu' ,90,'GOALKEEPER',transferuri[transferuri.length - 1].index + 1));
    transferuri.push(new transferPlayer('Tanase'     ,90,'MIDFIELDER',transferuri[transferuri.length - 1].index + 1));
}